#!/usr/bin/env bash
# Sim CLI — module-agnostic output helpers.
#
# Canonical results are JSON under <OUTPUT_DIR>/<check>.json (default
# sim/audit/reports/); Markdown, DOT and terminal text are rendered *views*
# of that JSON, never the source of truth.
# Reusable by any CLI module that produces structured results (audit today;
# doctor/graph/health later). Requires jq (already a CLI dependency).
#
# Bash 3 compatible.

# output_init — resolve the ephemeral output dir and ensure it exists.
# Module-agnostic: callers may export OUTPUT_DIR to redirect (e.g. a future
# `sim doctor` → sim/doctor/reports). Defaults to the audit module's reports dir.
output_init() {
  ROOT_DIR="${ROOT_DIR:-$(git rev-parse --show-toplevel)}"
  OUT_DIR="${OUTPUT_DIR:-$ROOT_DIR/sim/audit/reports}"
  mkdir -p "$OUT_DIR"
}

# output_result <check> <status> [json-payload]
# Persists canonical <OUTPUT_DIR>/<check>.json = {check,status} + payload, and
# prints a one-line terminal status row. status ∈ pass|fail|warn|skip.
output_result() {
  local check="$1" status="$2" payload="${3:-{}}"
  output_init
  printf '%s' "$payload" \
    | jq --arg c "$check" --arg s "$status" '{check:$c,status:$s} + .' \
    > "$OUT_DIR/$check.json"
  case "$status" in
    pass)      cli_row "$check" "pass" green ;;
    warn|skip) cli_row "$check" "$status" yellow ;;
    *)         cli_row "$check" "$status" red ;;
  esac
}

# output_render_md <summary.json>  → Markdown on stdout (a view of the JSON).
output_render_md() {
  local summary="$1"
  cat <<'EOF'
# Monorepo Audit — Baseline

_Generated by `sim audit --all`. Ephemeral — regenerated each run; never committed._

## Scorecard
| Check | Status |
|-------|--------|
EOF
  jq -r '.checks[] | "| \(.check) | \(.status) |"' "$summary"
  printf '\n## Details\n'
  jq -r '
    .checks[] |
    "\n### \(.check) — \(.status)\n" +
    ( (.counts // {}) | to_entries | map("- \(.key): \(.value)") | join("\n") ) +
    ( if (.note // "") != "" then "\n\n_" + .note + "_" else "" end )
  ' "$summary"
}

# output_aggregate — merge all per-check JSON into summary.json, render baseline.md.
output_aggregate() {
  output_init
  local files=() f
  for f in "$OUT_DIR"/*.json; do
    [ -e "$f" ] || continue
    [ "$(basename "$f")" = "summary.json" ] && continue
    files+=("$f")
  done
  [ "${#files[@]}" -eq 0 ] && return 0
  jq -s '{
    checks: .,
    total: length,
    passed: ([.[] | select(.status=="pass")] | length),
    failed: ([.[] | select(.status=="fail")] | length),
    warned: ([.[] | select(.status=="warn" or .status=="skip")] | length)
  }' "${files[@]}" > "$OUT_DIR/summary.json"
  output_render_md "$OUT_DIR/summary.json" > "$OUT_DIR/baseline.md"
}
