#!/usr/bin/env bash
# Sim CLI — installer/bootstrap shared library.
# Sourced by cli/setup.sh. Owns: paths/constants, shell + PATH detection,
# the XDG config/install records, repository fingerprinting, the managed PATH
# block, and the generator for the config-driven, self-healing launcher.
#
# Pure helpers only (no top-level side effects). Bash 3.2 compatible
# (macOS default): no `declare -A`, no `mapfile`, no `${var,,}`. jq-free.

# ─── Paths & constants ──────────────────────────────────────────────────────
SIM_CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/sim"
SIM_CONFIG="$SIM_CONFIG_DIR/config.json"
SIM_INSTALL="$SIM_CONFIG_DIR/install.json"
SIM_CACHE="$SIM_CONFIG_DIR/cache.json"
SIM_LOGS_DIR="$SIM_CONFIG_DIR/logs"
SIM_LOCAL_BIN="${XDG_BIN_HOME:-$HOME/.local/bin}"
SIM_LAUNCHER="$SIM_LOCAL_BIN/sim"

SIM_BLOCK_BEGIN="# >>> Sim CLI >>>"
SIM_BLOCK_END="# <<< Sim CLI <<<"
# Ownership marker embedded in every generated launcher. uninstall/relink only
# ever touch a launcher carrying this exact line.
SIM_LAUNCHER_SIGNATURE='# Sim launcher — generated by `pnpm sim`. Do not edit; re-run `pnpm sim`.'
SIM_CONFIG_VERSION=1
SIM_LAUNCHER_VERSION=1
SIM_HUSKY_MIN="9.1.0"
SIM_HOOKS_PATH="cli/husky/_"   # expected git core.hooksPath

# Recovery scan bounds (keep the launcher fast).
SIM_SCAN_DEPTH=4
SIM_MAX_CANDIDATES=50
SIM_SCAN_TIMEOUT=3
SIM_SCAN_ROOTS="$HOME/code $HOME/src $HOME/dev $HOME/workspace"

# ─── Small utilities ────────────────────────────────────────────────────────
sim_now_iso() { date -u +%Y-%m-%dT%H:%M:%SZ; }

# Extract a JSON string value: sim_json <file> <key>. Never fails (returns
# empty for a missing file) so callers stay safe under `set -euo pipefail`.
sim_json() {
  [[ -f "$1" ]] || return 0
  sed -n "s/.*\"$2\"[[:space:]]*:[[:space:]]*\"\([^\"]*\)\".*/\1/p" "$1" 2>/dev/null | head -1
}

# Extract a JSON numeric value: sim_json_num <file> <key> (unquoted numbers).
sim_json_num() {
  [[ -f "$1" ]] || return 0
  sed -n "s/.*\"$2\"[[:space:]]*:[[:space:]]*\([0-9][0-9]*\).*/\1/p" "$1" 2>/dev/null | head -1
}

# Append a timestamped line to a named log (install.log / recovery.log /
# doctor.log). Append-only, human-readable, best-effort.
sim_log_to() { # sim_log_to <logfile> <message>
  mkdir -p "$SIM_LOGS_DIR" 2>/dev/null || true
  printf '%s %s\n' "$(sim_now_iso)" "$2" >> "$SIM_LOGS_DIR/$1" 2>/dev/null || true
}
sim_log() { sim_log_to "install.log" "$1"; }  # back-compat default

# Age in whole days of an ISO-8601 (UTC) timestamp; empty if unparseable.
sim_age_days() { # sim_age_days <iso8601>
  local ts="$1" then now
  [[ -n "$ts" ]] || return 0
  then="$(date -u -d "$ts" +%s 2>/dev/null || date -u -j -f "%Y-%m-%dT%H:%M:%SZ" "$ts" +%s 2>/dev/null || true)"
  [[ -n "$then" ]] || return 0
  now="$(date -u +%s)"
  echo $(( (now - then) / 86400 ))
}

# Read the launcher version stamped into a generated launcher (empty if none).
sim_launcher_version() { # <launcherPath>
  [[ -f "$1" ]] || return 0
  sed -n 's/^# launcher-version: \([0-9][0-9]*\).*/\1/p' "$1" 2>/dev/null | head -1
}

# True if git's hooks path is the expected cli/husky/_.
sim_hooks_path() { git -C "$1" config core.hooksPath 2>/dev/null; }
sim_hooks_ok() { [[ "$(sim_hooks_path "$1")" == "$SIM_HOOKS_PATH" ]]; }

# ─── Environment detection ──────────────────────────────────────────────────
sim_os() { uname -s; }

# Sets SIM_SHELL_NAME and SIM_SHELL_RC from $SHELL. Never asks the user.
sim_detect_shell() {
  local sh="${SHELL:-}"
  case "$sh" in
    */zsh)  SIM_SHELL_NAME="zsh";  SIM_SHELL_RC="$HOME/.zshrc" ;;
    */bash) SIM_SHELL_NAME="bash"; SIM_SHELL_RC="$HOME/.bashrc" ;;
    */fish) SIM_SHELL_NAME="fish"; SIM_SHELL_RC="$HOME/.config/fish/config.fish" ;;
    *)      SIM_SHELL_NAME="${sh##*/}"; SIM_SHELL_RC="$HOME/.profile" ;;
  esac
}

# Shell-specific "reload this shell" command for activation guidance.
sim_reload_cmd() {
  case "$SIM_SHELL_NAME" in
    zsh|bash|fish) echo "exec $SIM_SHELL_NAME" ;;
    *)             echo "exec \$SHELL" ;;
  esac
}

# True if SIM_LOCAL_BIN is already on PATH.
sim_local_bin_on_path() {
  case ":$PATH:" in *":$SIM_LOCAL_BIN:"*) return 0 ;; *) return 1 ;; esac
}

# ─── Repository fingerprint ─────────────────────────────────────────────────
sim_repo_root() { git -C "${1:-$PWD}" rev-parse --show-toplevel 2>/dev/null; }
sim_repo_name() { sim_json "$1/package.json" name; }
sim_repo_remote() { git -C "$1" remote get-url origin 2>/dev/null; }

# is_sim_repo <dir> <expectedName> <expectedRemote>
# Structure must match AND identity (name or remote) must match — so we never
# bind to sim-old / -backup / -playground.
sim_is_repo() {
  local dir="$1" want_name="$2" want_remote="$3"
  [[ -n "$dir" && -f "$dir/cli/cli.sh" && -f "$dir/pnpm-workspace.yaml" ]] || return 1
  local name remote
  name="$(sim_repo_name "$dir")"
  remote="$(sim_repo_remote "$dir")"
  [[ -n "$want_name" && "$name" == "$want_name" ]] && return 0
  [[ -n "$want_remote" && "$remote" == "$want_remote" ]] && return 0
  return 1
}

# ─── Bounded recovery scan + cache ──────────────────────────────────────────
# Run a command with a wall-clock limit when timeout(1)/gtimeout(1) exists;
# otherwise run unbounded (best-effort, never errors on absence).
sim_timeout() { # <secs> cmd...
  local s="$1"; shift
  if command -v timeout >/dev/null 2>&1; then timeout "$s" "$@"
  elif command -v gtimeout >/dev/null 2>&1; then gtimeout "$s" "$@"
  else "$@"; fi
}

# Bounded filesystem scan for fingerprint-matching repos across the common dev
# roots. Depth-limited, candidate-capped, timeout-guarded. Deduped, order-preserved.
sim_scan_candidates() { # <wantName> <wantRemote>
  local want_name="$1" want_remote="$2" root cli cand count=0
  {
    for root in $SIM_SCAN_ROOTS; do
      [[ -d "$root" ]] || continue
      while IFS= read -r cli; do
        cand="$(cd "$(dirname "$(dirname "$cli")")" 2>/dev/null && pwd)" || continue
        if sim_is_repo "$cand" "$want_name" "$want_remote"; then
          echo "$cand"
          count=$((count + 1))
          [[ "$count" -ge "$SIM_MAX_CANDIDATES" ]] && break 2
        fi
      done < <(sim_timeout "$SIM_SCAN_TIMEOUT" find "$root" -maxdepth "$SIM_SCAN_DEPTH" -path '*/cli/cli.sh' 2>/dev/null)
    done
  } | awk '!seen[$0]++'
}

# Repository paths remembered from prior successful resolutions (cheap; tried
# before any filesystem scan).
sim_cache_paths() {
  [[ -f "$SIM_CACHE" ]] || return 0
  local last arr
  last="$(sim_json "$SIM_CACHE" lastSuccessfulPath)"
  arr="$(sed -n 's/.*"lastKnownRepositories"[[:space:]]*:[[:space:]]*\[\([^]]*\)\].*/\1/p' "$SIM_CACHE" 2>/dev/null | head -1)"
  { [[ -n "$last" ]] && echo "$last"
    printf '%s' "$arr" | tr ',' '\n' | sed 's/[[:space:]]//g; s/"//g; /^$/d'
  } | awk '!seen[$0]++'
}

# Persist the recovery cache. First arg is the last-successful path; it plus any
# extra known paths populate lastKnownRepositories (deduped, capped).
sim_write_cache() { # <lastSuccessfulPath> [knownPath...]
  mkdir -p "$SIM_CONFIG_DIR"
  local last="$1"; shift || true
  local p seen="" entries="" n=0
  for p in "$last" "$@"; do
    [[ -n "$p" ]] || continue
    case "$seen" in *"|$p|"*) continue ;; esac
    seen="$seen|$p|"
    entries="$entries${entries:+, }\"$p\""
    n=$((n + 1)); [[ "$n" -ge "$SIM_MAX_CANDIDATES" ]] && break
  done
  cat > "$SIM_CACHE" <<EOF
{
  "version": $SIM_CONFIG_VERSION,
  "lastSuccessfulPath": "$last",
  "lastRecovery": "$(sim_now_iso)",
  "lastKnownRepositories": [$entries]
}
EOF
}

# ─── Config / install records ───────────────────────────────────────────────
sim_write_config() { # <repoPath> <name> <remote>
  mkdir -p "$SIM_CONFIG_DIR"
  cat > "$SIM_CONFIG" <<EOF
{
  "version": $SIM_CONFIG_VERSION,
  "repoPath": "$1",
  "workspaceName": "$2",
  "gitRemote": "$3",
  "installedAt": "$(sim_now_iso)"
}
EOF
}

sim_write_install() { # <launcherPath> <shellRc> <managedBlockAdded:true|false> <cliVersion>
  mkdir -p "$SIM_CONFIG_DIR"
  cat > "$SIM_INSTALL" <<EOF
{
  "version": $SIM_CONFIG_VERSION,
  "launcherPath": "$1",
  "shellRc": "$2",
  "managedBlockAdded": $3,
  "cliVersion": "$4",
  "installedAt": "$(sim_now_iso)"
}
EOF
}

# ─── Managed PATH block ─────────────────────────────────────────────────────
sim_block_present() { # <rcFile>
  [[ -f "$1" ]] && grep -qF "$SIM_BLOCK_BEGIN" "$1"
}

# Idempotent: adds the block only when absent. Returns 0 if it wrote, 1 if it
# was already present (no change).
sim_add_block() { # <rcFile>
  local rc="$1"
  sim_block_present "$rc" && return 1
  mkdir -p "$(dirname "$rc")"
  { printf '\n%s\n' "$SIM_BLOCK_BEGIN"
    printf 'export PATH="%s:$PATH"\n' "\$HOME/.local/bin"
    printf '%s\n' "$SIM_BLOCK_END"
  } >> "$rc"
  return 0
}

# Removes the marker-delimited block, leaving everything else untouched.
sim_remove_block() { # <rcFile>
  local rc="$1"
  [[ -f "$rc" ]] || return 0
  sim_block_present "$rc" || return 0
  local tmp; tmp="$(mktemp)"
  sed "/^$SIM_BLOCK_BEGIN\$/,/^$SIM_BLOCK_END\$/d" "$rc" > "$tmp" && mv "$tmp" "$rc"
}

# ─── Launcher generation ────────────────────────────────────────────────────
sim_launcher_is_ours() { # <path>
  [[ -f "$1" ]] && grep -qF "$SIM_LAUNCHER_SIGNATURE" "$1"
}

# Writes the generic, config-driven, self-healing launcher to SIM_LAUNCHER.
# Contains NO repository path — it reads ~/.config/sim/config.json at runtime
# and self-heals (walk-up → cache → bounded scan → relink) on a move. Recovery
# is bounded (depth/cap/timeout, early-exit) and updates the recovery cache.
sim_generate_launcher() {
  mkdir -p "$SIM_LOCAL_BIN"
  cat > "$SIM_LAUNCHER" <<LAUNCHER
#!/usr/bin/env bash
$SIM_LAUNCHER_SIGNATURE
# launcher-version: $SIM_LAUNCHER_VERSION
set -euo pipefail

DIR="\${XDG_CONFIG_HOME:-\$HOME/.config}/sim"
CONFIG="\$DIR/config.json"; CACHE="\$DIR/cache.json"; LOGS="\$DIR/logs"
SCAN_DEPTH=$SIM_SCAN_DEPTH; MAX_CAND=$SIM_MAX_CANDIDATES; SCAN_TO=$SIM_SCAN_TIMEOUT

_json() { [[ -f "\$1" ]] || return 0; sed -n "s/.*\"\$2\"[[:space:]]*:[[:space:]]*\"\([^\"]*\)\".*/\1/p" "\$1" 2>/dev/null | head -1; }

[[ -f "\$CONFIG" ]] || { echo "❌ Sim is not installed on this machine. Run: pnpm cli" >&2; exit 1; }

REPO="\$(_json "\$CONFIG" repoPath)"
WS="\$(_json "\$CONFIG" workspaceName)"
REMOTE="\$(_json "\$CONFIG" gitRemote)"

_is_repo() {
  local d="\$1" name remote
  [[ -n "\$d" && -f "\$d/cli/cli.sh" && -f "\$d/pnpm-workspace.yaml" ]] || return 1
  name="\$(sed -n 's/.*"name"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' "\$d/package.json" 2>/dev/null | head -1)"
  remote="\$(git -C "\$d" remote get-url origin 2>/dev/null || true)"
  [[ -n "\$WS" && "\$name" == "\$WS" ]] && return 0
  [[ -n "\$REMOTE" && "\$remote" == "\$REMOTE" ]] && return 0
  return 1
}

_timeout() { local s="\$1"; shift; if command -v timeout >/dev/null 2>&1; then timeout "\$s" "\$@"; elif command -v gtimeout >/dev/null 2>&1; then gtimeout "\$s" "\$@"; else "\$@"; fi; }

_cache_paths() {
  [[ -f "\$CACHE" ]] || return 0
  { _json "\$CACHE" lastSuccessfulPath
    sed -n 's/.*"lastKnownRepositories"[[:space:]]*:[[:space:]]*\[\([^]]*\)\].*/\1/p' "\$CACHE" 2>/dev/null | head -1 | tr ',' '\n' | sed 's/[[:space:]]//g; s/"//g'
  } | sed '/^\$/d' | awk '!seen[\$0]++'
}

_write() { # <newRepoPath>
  local new="\$1" tmp
  tmp="\$(mktemp)"; sed "s#\"repoPath\"[[:space:]]*:[[:space:]]*\"[^\"]*\"#\"repoPath\": \"\$new\"#" "\$CONFIG" > "\$tmp" && mv "\$tmp" "\$CONFIG"
  mkdir -p "\$DIR" "\$LOGS" 2>/dev/null || true
  printf '{\n  "version": 1,\n  "lastSuccessfulPath": "%s",\n  "lastRecovery": "%s",\n  "lastKnownRepositories": ["%s"]\n}\n' \
    "\$new" "\$(date -u +%Y-%m-%dT%H:%M:%SZ)" "\$new" > "\$CACHE" 2>/dev/null || true
  printf '%s relink repoPath -> %s\n' "\$(date -u +%Y-%m-%dT%H:%M:%SZ)" "\$new" >> "\$LOGS/recovery.log" 2>/dev/null || true
}

if ! _is_repo "\$REPO"; then
  found=""
  # 2. walk up from CWD (early-exit on first fingerprint match).
  d="\$PWD"
  while [[ "\$d" != "/" && "\$d" != "." ]]; do
    if _is_repo "\$d"; then found="\$d"; break; fi
    d="\$(dirname "\$d")"
  done
  # 3. cached candidates (cheap; early-exit on first still-valid).
  if [[ -z "\$found" ]]; then
    while IFS= read -r c; do
      [[ -n "\$c" ]] || continue
      if _is_repo "\$c"; then found="\$c"; break; fi
    done < <(_cache_paths)
  fi
  # 4. bounded filesystem scan (depth/cap/timeout); accept only if unambiguous.
  if [[ -z "\$found" ]]; then
    matches=""; n=0
    for root in "\$HOME/code" "\$HOME/src" "\$HOME/dev" "\$HOME/workspace"; do
      [[ -d "\$root" ]] || continue
      while IFS= read -r cli; do
        cand="\$(dirname "\$(dirname "\$cli")")"
        if _is_repo "\$cand"; then matches="\$matches\$cand"$'\n'; n=\$((n+1)); [[ \$n -ge \$MAX_CAND ]] && break; fi
      done < <(_timeout "\$SCAN_TO" find "\$root" -maxdepth "\$SCAN_DEPTH" -path '*/cli/cli.sh' 2>/dev/null)
    done
    matches="\$(printf '%s' "\$matches" | awk '!seen[\$0]++' | sed '/^\$/d')"
    cnt="\$(printf '%s\n' "\$matches" | sed '/^\$/d' | wc -l | tr -d ' ')"
    if [[ "\$cnt" == "1" ]]; then found="\$matches"
    elif [[ "\$cnt" -gt 1 ]]; then
      echo "⚠ Multiple Sim repositories found. Run: pnpm cli" >&2; exit 1
    fi
  fi
  # 5. give up with guidance.
  if [[ -z "\$found" ]]; then
    echo "❌ Sim repository not found (configured: \$REPO)." >&2
    echo "ℹ️  cd into the repo and run 'pnpm cli'." >&2
    exit 1
  fi
  # relink confirm (interactive); auto-relink when non-interactive (CI).
  if [[ "\$found" != "\$REPO" ]]; then
    if [[ -t 0 && -t 1 ]]; then
      printf '⚠ Sim repository moved.\n\n  Previous:\n    %s\n\n  Detected:\n    %s\n\nUpdate configuration? [Y/n] ' "\$REPO" "\$found"
      read -r ans || ans="Y"
      case "\${ans:-Y}" in [Nn]*) echo "Aborted; configuration unchanged." >&2; exit 1 ;; esac
    fi
    _write "\$found"; REPO="\$found"
  fi
fi

exec bash "\$REPO/cli/cli.sh" "\$@"
LAUNCHER
  chmod +x "$SIM_LAUNCHER"
}

# ─── Husky version gate ─────────────────────────────────────────────────────
# Reads the installed husky version from node_modules; echoes it (or empty).
sim_husky_version() { # <repoRoot>
  sim_json "$1/node_modules/husky/package.json" version
}

# semver >= compare: sim_semver_ge <have> <min>  → 0 if have >= min
sim_semver_ge() {
  local have="$1" min="$2"
  local h1 h2 h3 m1 m2 m3
  IFS=. read -r h1 h2 h3 <<< "$have"
  IFS=. read -r m1 m2 m3 <<< "$min"
  h1=${h1:-0}; h2=${h2:-0}; h3=${h3:-0}; m1=${m1:-0}; m2=${m2:-0}; m3=${m3:-0}
  if [[ "$h1" -ne "$m1" ]]; then [[ "$h1" -gt "$m1" ]]; return; fi
  if [[ "$h2" -ne "$m2" ]]; then [[ "$h2" -gt "$m2" ]]; return; fi
  [[ "$h3" -ge "$m3" ]]
}
