// Domain
export * from '#domain/entities/memory.entity'
export * from '#domain/entities/memory-candidate.entity'
export * from '#domain/entities/memory-evidence.entity'
export * from '#domain/entities/memory-consent.entity'
export * from '#domain/judgment/memory-judgment'
export * from '#domain/policies/memory-acceptance.policy'
export * from '#domain/value-objects/memory-economics.value-object'
export * from '#domain/value-objects/memory-identifiers.value-object'

// Application contracts and ports
export * from '#application/contracts/memory-curation.contract'
export * from '#application/contracts/memory-curation-authorization.contract'
export * from '#application/contracts/memory-retrieval.contract'
export * from '#application/contracts/memory-retrieval.error'
export * from '#application/ports/memory-authorization.port'
export * from '#application/ports/memory-curation-persistence.port'
export * from '#application/ports/memory-extractor.port'
export * from '#application/ports/memory-repository.port'
export * from '#application/ports/memory-retrieval-observer.port'
export * from '#application/ports/canonical-memory.port'
export * from '#application/ports/candidate-resolution.port'
export * from '#application/ports/consent-ledger.port'
export * from '#application/ports/observability.port'
export * from '#application/ports/model-pricing.port'

// Application use cases
export * from '#application/use-cases/curate-memory.use-case'
export * from '#application/use-cases/memory-curation.handler'
export * from '#application/use-cases/retrieve-memory.use-case'
export * from '#application/use-cases/accept-memory-candidate.use-case'
export * from '#application/use-cases/resolve-memory-candidate.use-case'
export * from '#application/use-cases/forget-memory.use-case'
export * from '#application/use-cases/measure-memory-economics.use-case'

// Infrastructure adapters intentionally exported only for composition roots/tests.
export * from '#infrastructure/adapters/inference/langchain-memory-extractor.adapter'
export * from '#infrastructure/adapters/persistence/postgres/postgres-memory.repository.adapter'
export * from '#infrastructure/adapters/persistence/postgres/postgres-memory-curation.adapter'
export * from '#infrastructure/adapters/persistence/postgres/postgres-canonical-memory.repository.adapter'
export * from '#infrastructure/adapters/persistence/postgres/postgres-candidate-resolution.repository.adapter'
export * from '#infrastructure/adapters/persistence/postgres/postgres-consent-ledger.repository.adapter'
export * from '#infrastructure/adapters/observability/repo-observability.adapter'
export * from '#infrastructure/adapters/testing/in-memory-memory.repository.adapter'
export * from '#infrastructure/adapters/testing/in-memory-memory-authorization.adapter'
export * from '#infrastructure/adapters/testing/in-memory-curation-authorization.adapter'
export * from '#infrastructure/database/postgres-executor'
