import { randomBytes } from 'node:crypto'
import { access, writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { spawn, spawnSync } from 'node:child_process'

const runtimeDirectory = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const composeFile = resolve(runtimeDirectory, 'compose.yaml')
const environmentFile = resolve(runtimeDirectory, '.env')

const composeActions = {
  config: ['config'],
  down: ['down', '--remove-orphans'],
  logs: ['logs', '--follow', '--tail=100'],
  ps: ['ps'],
  up: ['up', '--build', '--remove-orphans']
} as const

type ComposeAction = keyof typeof composeActions

async function main(): Promise<void> {
  const rawArguments = process.argv.slice(2)
  const normalizedArguments =
    rawArguments[0] === '--' ? rawArguments.slice(1) : rawArguments
  const [firstArgument, ...remainingArguments] = normalizedArguments
  const action = isComposeAction(firstArgument) ? firstArgument : 'up'
  const forwardedArguments = isComposeAction(firstArgument)
    ? remainingArguments
    : firstArgument
      ? [firstArgument, ...remainingArguments]
      : remainingArguments

  if (
    firstArgument &&
    !firstArgument.startsWith('-') &&
    !isComposeAction(firstArgument)
  ) {
    printUsage(`Ação desconhecida: ${firstArgument}`)
    process.exitCode = 1
    return
  }

  assertDockerComposeIsAvailable()
  await ensureLocalEnvironment()

  if (action === 'up') {
    console.info(
      '[runtime] Subindo PostgreSQL, Redis, landing, console, onboarding e mobile. Use Ctrl+C para encerrar.'
    )
  }

  const exitCode = await runCompose(action, forwardedArguments)
  process.exitCode = exitCode
}

function isComposeAction(value: string | undefined): value is ComposeAction {
  return value !== undefined && value in composeActions
}

function assertDockerComposeIsAvailable(): void {
  const result = spawnSync('docker', ['compose', 'version'], {
    cwd: runtimeDirectory,
    stdio: 'ignore'
  })

  if (result.error || result.status !== 0) {
    throw new Error(
      'Docker Compose v2 não foi encontrado. Instale ou inicie o Docker e tente `pnpm runtime` novamente.'
    )
  }
}

async function ensureLocalEnvironment(): Promise<void> {
  try {
    await access(environmentFile)
    return
  } catch {
    // The local file is generated below and is ignored by Git.
  }

  const contents = [
    '# Generated by `pnpm runtime`. Local development only.',
    'POSTGRES_DB=amarelo',
    'POSTGRES_USER=amarelo',
    `POSTGRES_PASSWORD=${randomBytes(32).toString('base64url')}`,
    'POSTGRES_PORT=5432',
    `REDIS_PASSWORD=${randomBytes(32).toString('base64url')}`,
    'REDIS_PORT=6379',
    'LANDING_PORT=3000',
    'CONSOLE_PORT=3001',
    'ONBOARDING_PORT=3002',
    'MOBILE_PORT=3003',
    ''
  ].join('\n')

  try {
    await writeFile(environmentFile, contents, {
      encoding: 'utf8',
      flag: 'wx',
      mode: 0o600
    })
    console.info(
      '[runtime] Credenciais locais aleatórias criadas em workspaces/packages/runtime/.env.'
    )
  } catch (error) {
    if (!isAlreadyExistsError(error)) {
      throw error
    }
  }
}

function isAlreadyExistsError(error: unknown): error is NodeJS.ErrnoException {
  return error instanceof Error && 'code' in error && error.code === 'EEXIST'
}

async function runCompose(
  action: ComposeAction,
  forwardedArguments: string[]
): Promise<number> {
  const composeArguments = [
    'compose',
    '--project-name',
    'amarelo-dev',
    '--env-file',
    environmentFile,
    '--file',
    composeFile,
    ...composeActions[action],
    ...forwardedArguments
  ]

  const child = spawn('docker', composeArguments, {
    cwd: runtimeDirectory,
    stdio: 'inherit'
  })

  const forwardSignal = (signal: NodeJS.Signals) => {
    if (!child.killed) {
      child.kill(signal)
    }
  }

  process.once('SIGINT', forwardSignal)
  process.once('SIGTERM', forwardSignal)

  return await new Promise<number>((resolvePromise, rejectPromise) => {
    child.once('error', rejectPromise)
    child.once('close', (code, signal) => {
      process.removeListener('SIGINT', forwardSignal)
      process.removeListener('SIGTERM', forwardSignal)

      if (signal) {
        resolvePromise(signal === 'SIGINT' ? 130 : 143)
        return
      }

      resolvePromise(code ?? 1)
    })
  })
}

function printUsage(message: string): void {
  console.error(`[runtime] ${message}`)
  console.error(
    'Uso: pnpm runtime -- [up|down|logs|ps|config] [opções do Docker Compose]'
  )
}

main().catch((error: unknown) => {
  const message = error instanceof Error ? error.message : String(error)
  console.error(`[runtime] ${message}`)
  process.exitCode = 1
})
